title: Ruijia Kuang's Homepage
page-top-title: Ruijia Kuang
top-section-bg-text: Computer Science
home-subtitle: Ruijia Kuang&ensp;|&ensp;邝锐嘉
copyright-text: '&copy; Ruijia Kuang 2023-2024. All Rights Reserved.'
